#!/bin/sh

if [ ! -e pkg-descr ]; then
    printf "$0 must be run from the port directory.\n"
    exit 1
fi

# Determine WRKSRC
PORTNAME=`awk '$1 == "PORTNAME=" { print $2 }' Makefile`
PORTVERSION=`awk '$1 == "PORTVERSION=" { print $2 }' Makefile`
if egrep -q '^WRKSRC=' Makefile; then
    WRKSRC=`awk '$1 == "WRKSRC=" { print $2 }' Makefile`
    printf "Raw WRKSRC = %s\n" $WRKSRC
elif egrep -q '^DISTNAME=' Makefile; then
    WRKSRC=work/`awk '$1 == "DISTNAME=" { print $2 }' Makefile`
else
    WRKSRC=work/${PORTNAME}-${PORTVERSION}
fi
WRKSRC=`echo $WRKSRC | sed -e 's|${WRKDIR}|work|g' \
    -e 's|${PORTNAME}|'$PORTNAME'|g' \
    -e 's|${PORTVERSION}|'$PORTVERSION'|g'`

printf "WRKSRC = %s\n" $WRKSRC

mkdir -p files
port_dir=`pwd`

# Go to WRKSRC and generate patch file
cd ${WRKSRC}
pwd
list=`find * -name '*.orig'`
for file in ${list}; do
    echo ${file} ${file%.orig}
    patch_file='patch-'`echo ${file%.orig} | sed -e 's|/|-|g'`
    diff -u ${file} ${file%.orig} > ${port_dir}/files/$patch_file
done

