#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 filename\n"
    exit 1
fi

file="$1"
if [ ! -e "$file" ]; then
    printf "%s: No such file.\n" "$file"
    exit 1
fi

if [ ! -e "$file.orig" ]; then
    cp "$file" "$file.orig"
fi

vi "$file"

printf 'Regenerate patch file? (y/n) '
read resp
if [ 0$resp = 0y ]; then
    port-mkpatch "$file"
fi

