#!/bin/sh -e

##########################################################################
#   Script description:
#       Commit a port via git
#       
#   History:
#   Date        Name        Modification
#   2021-04-12  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 category/port [category/Makefile]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ] && [ $# != 2 ]; then
    usage
fi

printf "Comitting...\n"
git commit $@
printf "Stashing local mods...\n"
git stash push Mk/bsd.local.mk
printf "Pulling and rebasing...\n"
git pull -r
printf "Pushing commits...\n"
git push
printf "Unstashing...\n"
git stash pop
