#!/bin/sh -e

##########################################################################
#   Synopsis:
#       port-diff [port-name]
#       
#   Description:
#       .B port-diff
#       runs "diff -ruN" between the committed port and the current working
#       directory.  The path of the committed port is determined using
#       CATEGORIES and the directory name of the CWD.
#       
#   Arguments:
#       port-name   Name of port if different from CWD
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       port-check(1), port-create(1), port-mkpatch(1), port-patch-edit(1)
#       port-remake(1), port-reinstall(1), port-restage(1)
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 64     # sysexits(3) EX_USAGE
}


##########################################################################
#   Main
##########################################################################

if [ $# -gt 1 ]; then
    usage
fi

if [ ! -e pkg-descr ] && ! fgrep -q MASTERDIR Makefile; then
    printf "You must run this script from within port directory.\n"
    exit 1
fi

if [ 0$PORTSDIR = 0 ]; then
    PORTSDIR=/usr/ports
fi

portname=$(basename $(pwd))
category=$(awk '$1 == "CATEGORIES=" { print $3 }' Makefile)
if [ 0$category = 0 ] || [ ! -e $PORTSDIR/$category ]; then
    printf "The category of the commited port must be listed second in CATEGORIES.\n"
    exit 1
fi

if [ $# = 1 ]; then
    old_portname=$1
else
    old_portname=$portname
fi

if [ ! -e /usr/ports/$category/$old_portname ]; then
    printf "Error: /usr/ports/$category/$old_portname does not exist.\n"
    exit 1
fi

save_cwd=`pwd`
if [ -e work ]; then
    mv work ../work.$portname
fi
if grep -q '^CATEGORIES.*wip' Makefile; then
    wip=1
    sed -i .bak -e "/^CATEGORIES/s|wip ||" Makefile
    mv Makefile.bak /tmp/Makefile.bak.$portname
fi
rm -f patch.$portname
if ! diff -ruN --exclude=CVS --exclude=.svn \
	  /usr/ports/$category/$old_portname `pwd`; then
    # Send patch direct to file.  Copy and paste from terminal may convert
    # tabs to spaces.
    diff -ruN --exclude=CVS --exclude=.svn \
	  /usr/ports/$category/$old_portname `pwd` > patch.$portname || true
    printf "Patch saved to patch.$portname.\n"
    if [ 0$wip = 01 ]; then
	mv /tmp/Makefile.bak.$portname Makefile
    fi
else
    printf "No differences found.\n"
    if [ 0$wip = 01 ]; then
	mv /tmp/Makefile.bak.$portname Makefile
    fi
    exit 1
fi
if [ -e ../work.$portname ]; then
    mv ../work.$portname work
fi

category=$(basename $(dirname $(pwd)))

cat << EOM
===

Submit a PR with the diff above.

Summary examples: See porter's guide for details.
    
    You are maintainer:
    
    [new port] $category/$portname: short description of port
    [maintainer update] $category/$portname: short description of change
    
    You are not maintainer:
    
    [change request] $category/$portname: short description of change

Category:   ports

Class:      New port:   change-request
	    Update:     maintainer update if you're the maintainer
			change-request if not
	    
EOM

if [ -e pkg-descr ]; then
    printf "\npkg-descr:\n\n"
    cat pkg-descr
else
    printf 'WARNING: No pkg-descr.\n'
fi
printf '\n'
