#!/bin/sh -e

##########################################################################
#   Synopsis:
#       port-create port-name category maintainer
#       
#   Description:
#       .B port-create
#       Generates a skeletal new FreeBSD port under the current
#       working directory (which should normally be $PORTSDIR/wip).
#       It is a simple time-saving tool to reduce typing.
#       The next step is usually to run wip-edit(1) within the
#       new port directory, to flesh out Makefile, pkg-descr, etc.
#       
#   Arguments:
#       port-name   Directory name for the new port
#       category    Main category for the new port, inserted into Maekfile
#       maintainer  Email address of the port maintainer
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   Examples:
#       port-create fastq-trim biology jwb@FreeBSD.org
#
#   See also:
#       port-check(1), port-diff(1), port-mkpatch(1), port-patch-edit(1)
#       port-remake(1), port-restage(1), port-reinstall(1)
##########################################################################

usage()
{
    printf "Usage: $0 port-name category maintainer\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 3 ]; then
    usage
fi
port=$1
category=$2
maintainer=$3

mkdir $port
cd $port

tab="$(printf '\t')"

if echo $port | grep '^py-'; then
    cat << EOM > Makefile
PORTNAME=${tab}${port#py-}
DISTVERSION=${tab}
CATEGORIES=${tab}wip $category python
MASTER_SITES=${tab}PYPI
PKGNAMEPREFIX=${tab}\${PYTHON_PKGNAMEPREFIX}

MAINTAINER=${tab}$maintainer
COMMENT=${tab}
WWW=${tab}${tab}https://pypi.python.org/project/${port#py-}/

LICENSE=${tab}
LICENSE_FILE=${tab}

USES=${tab}${tab}python
USE_PYTHON=${tab}autoplist distutils

.include <bsd.port.mk>
EOM

    cat << EOM > pkg-descr
[description of the port]
EOM

else

cat << EOM > Makefile
PORTNAME=${tab}$port
DISTVERSION=${tab}
CATEGORIES=${tab}wip $category
MASTER_SITES=${tab}

MAINTAINER=${tab}$maintainer
COMMENT=${tab}
WWW=${tab}${tab}https://example.com/$port

LICENSE=${tab}
LICENSE_FILE=${tab}

.include <bsd.port.mk>
EOM

    cat << EOM > pkg-descr
[description of the port]
EOM

fi
