#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

if ! grep -q '^DEVELOPER=' /etc/make.conf; then
    printf 'DEVELOPER=yes\n' >> /etc/make.conf
fi

: ${PORTSDIR:=/usr/ports}
if [ $# = 1 ]; then
    cd $PORTSDIR/$1
fi

printf "Remove distfile? y/[n] "
read distclean
if [ 0$distclean = 0y ]; then
    make distclean
else
    make clean
fi
if ! portlint -AC; then
    read -p 'Continue? y/[n] ' continue
    if [ 0$continue != 0y ]; then
	exit
    fi
else
    pause
fi
make deinstall
make rmconfig
make reinstall
make check-plist
make stage-qa
read -p "Clean? y/[n] " clean
if [ 0$clean = 0y ]; then
    make clean
fi
