#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

while echo $1 | grep -q '^-'; do
    if [ 0$1 = 0--no-commit ]; then
	no_commit=1
    elif [ 0$1 = 0--no-check ]; then
	no_check=1
    fi
    shift
done

case $# in
0)
    ;;

1)
    : ${PORTSDIR:=/usr/ports}
    cd $PORTSDIR/$1
    ;;

*)
    printf "Usage: $0 [--no-commit] [--no-check] [category/port]\n"
    exit 1
esac

: ${EDITOR:=vi}

pwd

printf "Remove distfile[s]? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    make distclean
else
    make clean
fi

# Check for metaports
if fgrep -q MASTER_SITES Makefile || fgrep -q USE_GIT Makefile; then
    rm -f distinfo
    make makesum
fi

env BATCH=1 make depends

if [ -e pkg-plist ]; then
    printf "Regenerate plist? y/[n] "
    read regen
    if [ 0$regen = 0y ]; then
	make clean stage
	make makeplist > pkg-plist.new
	$EDITOR pkg-plist.new
	printf "Diff:\n"
	if ! diff -u pkg-plist pkg-plist.new; then
	    while [ 0$new_plist != 0i ]; do
		printf "(i)nstall new plist (e)dit (a)bort "
		read new_plist
		if [ 0$new_plist = 0i ]; then
		    mv -f pkg-plist.new pkg-plist
		elif [ 0$new_plist = 0e ]; then
		    $EDITOR pkg-plist.new
		    diff -u pkg-plist pkg-plist.new || true
		elif [ 0$new_plist = 0a ]; then
		    exit 0
		else
		    printf "Invalid selection.\n"
		fi
	    done
	    make clean
	else
	    printf "No changes to pkg-plist.\n"
	    rm -f pkg-plist.new
	fi
    fi
fi

if [ -z "$no_check" ]; then
    cat << EOM

=====================
Running port-check...
=====================

EOM
    port-check
fi

if [ 0$no_commit != 01 ]; then
    printf "Commit changes to port? y/[n] "
    read commit
    if [ 0$commit = 0y ]; then
	printf "Updating repo...\n"
	if [ -e ../.svn ]; then
	    svn up
	elif [ -e ../.git ]; then
	    git pull --rebase=false
	else
	    printf "This is neither a subversion nor a git repository.\n"
	    exit 1
	fi
	printf "Comitting changes...\n"
	if [ -e ../.svn ]; then
	    svn ci .
	elif [ -e ../.git ]; then
	    git commit .
	    git push
	fi
    fi
fi
