#!/bin/sh

for dir in /usr/ports /usr/wip; do
    if [ -d $dir ]; then
	for category in $dir/*; do
	    echo $category
	    if [ -e $category/Makefile ] && [ $category != /usr/ports/Templates ]; then
		fgrep $@ $category/*/Makefile
	    fi
	done
    fi
done

