#!/bin/sh -e

if [ -z $EDITOR ]; then
    export EDITOR=vi
fi

# Avoid perm issues as poudriere runs as nobody
umask 022

if ! which poudriere > /dev/null; then
    pkg install -y poudriere
fi

etc=/usr/local/etc
conf=$etc/poudriere.conf
poudriere=/usr/local/poudriere

if [ ! -e $conf ]; then
    cp $conf.sample $conf
fi

printf "Use ZFS? [y]/n "
read use_zfs
if [ 0"$use_zfs" = 0n ]; then
    sed -i '' -e 's|^#NO_ZFS=|NO_ZFS=|' $conf
else
    df
    default_zpool=`awk -F = '$1 == "ZPOOL" { print $2 }' $conf`
    printf "ZFS pool? [$default_zpool] "
    read zpool
    if [ -z "$zpool" ]; then
	zpool=$default_zpool
    fi
    sed -i '' -e "s|^ZPOOL.*|ZPOOL=$zpool|" $conf     # If already enabled
    sed -i '' -e "s|^#ZPOOL.*|ZPOOL=$zpool|" $conf
fi
$EDITOR $conf

# mirror=`auto-fastest-mirror`
mirror='https://download.FreeBSD.org'
sed -i '' -e "s|_PROTO_://_CHANGE_THIS_|$mirror|" $conf
sed -i '' -e "s|^#POUDRIERE_DATA=|POUDRIERE_DATA=|" $conf
sed -i '' -e "s|^#CCACHE_DIR==|CCACHE_DIR=|" $conf

mkdir -p $poudriere/data
if [ ! -e $poudriere/ports/default ]; then
    # Check out ports tree
    poudriere ports -c -m git+https -B main
fi

# Allow use of bsd.local.mk
auto-append-line 'USE_LOCAL_MK=yes' $etc/poudriere.d/make.conf $0

# Allow wip category
auto-append-line 'VALID_CATEGORIES+=wip' \
    $poudriere/ports/default/Mk/bsd.local.mk $0

another=y
while [ 0$another = 0y ]; do
    printf "Existing poudriere jails:\n\n"
    poudriere jail -l

    cat << EOM

On amd64 systems, you can create either amd64 or i386 jails.

For other architectures, accept the default below.

EOM
    default_arch=`uname -p`
    printf "Processor architecture? [$default_arch] "
    read arch
    if [ 0$arch = 0 ]; then
	arch=$default_arch
    fi

    cat << EOM

You can select any release equal to or older than the default shown below.

EOM
    
    default_release=`uname -r`
    default_release=${default_release%-p*}
    printf "Release? [$default_release] "
    read release
    if [ 0$release = 0 ]; then
	release=$default_release
    fi
    
    default_name=`echo $release | cut -d - -f 1 | tr '.' '-'`-$arch
    printf "Jail name? [$default_name] "
    read name
    if [ 0$name = 0 ]; then
	name=$default_name
    fi
    
    if [ ! -e $poudriere/jails/$name ]; then
	set -x
	poudriere jail -c -j "$name" -v $release || true
	set +x
    else
	printf "Jail $name already exists.\n"
    fi
    
    if [ $arch = amd64 ]; then
	name=`echo $release | cut -d - -f 1 | tr '.' '-'`-i386
	printf "Create $name as well? y/[n] "
	read i386
	if [ 0"$i386" = 0y ]; then
	    poudriere jail -c -j "$name" -v $release -a i386 || true
	fi
    fi
    
    printf "Create another jail for an older release? y/[n] "
    read another
done
