#!/bin/sh -e

cat << EOM

Note: Jails cannot be newer than the host system.

If your host system is not fully up-to-date, run auto-update-system first.

EOM
read -p "Is your host system up-to-date? y/[n] " up2date
if [ 0$up2date = 0y ]; then
    umask 022   # Make sure Mk files are readable to "nobody"
    for jail in `poudriere jail -ql | awk '{ print $1 }'`; do
	printf "$jail\n"
	poudriere jail -u -j $jail
    done
    : ${POUDRIERE_PORTS:=/usr/local/poudriere/ports/default}
    cd $POUDRIERE_PORTS

    # bsd.local.mk has been moved to bsd.local.mk.sample.
    # If ports tree is out of date, it may still be tracked.
    stash_file=Mk/bsd.local.mk
    if git ls-files --error-unmatch $stash_file > /dev/null 2>&1 \
	&& ! git diff --quiet $stash_file; then
	stash=1
    fi
    if [ 0$stash = 01 ]; then
	printf "Stashing $stash_file...\n"
	git stash push $stash_file || true
    fi
    poudriere ports -u
    if [ 0$stash = 01 ]; then
	printf "Unstashing...\n"
	git stash pop || true   # Returns non-zero if nothing stashed
    fi
else
    # Terminate caller (e.g. wip-poudriere-test) if user selects poudriere
    # update and says system is out of date
    exit 1
fi
