#!/bin/sh -e

: ${PORTSDIR:=/usr/ports}
cd $PORTSDIR

# bsd.local.mk has been moved to bsd.local.mk.sample.
# If ports tree is out of date, it may still be tracked.
stash_file=Mk/bsd.local.mk
if git ls-files --error-unmatch $stash_file > /dev/null 2>&1 \
    && ! git diff --quiet $stash_file; then
    stash=1
fi
if [ 0$stash = 01 ]; then
    printf "Stashing $stash_file...\n"
    git stash push Mk/$stash_file || true
fi

printf "Pulling and rebasing...\n"
git pull -r

printf "Pushing commits...\n"
git push

if [ 0$stash = 01 ]; then
    printf "Unstashing...\n"
    git stash pop || true   # Returns non-zero if nothing stashed
fi


