#!/bin/sh -e

##########################################################################
#   Script description:
#       Search files in ports/pkgsrc frameworks.
#
#   Note:
#       Keep port-grep and pkg-grep in sync!
#
#   Arguments:
#       -p prefix (default /usr/ports or /usr/pkgsrc)
#       -f file (default Makefile)
#
#   History:
#   Date        Name        Modification
#   2015-04-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-p prefix] [-f file] regular-expression [grep flags]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `basename $0` = port-grep ]; then
    prefix=/usr/ports
else
    prefix=$(auto-pkgsrc-dir)
fi

# Overwrite later if provided as an argument
filename='Makefile'

while [ 0`echo $1 | cut -c 1-1` = 0'-' ]; do
    case "$1" in
    -p)
	prefix=$2
	shift
	shift
	;;
    -f)
	filename="$2"
	shift
	shift
	;;
    *)
	usage
	;;
    esac
done

if [ $# -lt 1 ]; then
    usage
fi

re="$1"
shift
grep_flags="$@"

set +e
find $prefix -name $filename -depth 3 | xargs grep $grep_flags "$re"
