#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-11-10  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 filename\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

filename="$1"

if [ ! -e pkg-descr ]; then
    printf "$0 must be run from the port directory.\n"
    exit 1
fi

if [ ! -e "$filename.orig" ]; then
    printf "Error: No $filename.orig present.\n"
    exit 1
fi

# Determine WRKSRC
# FIXME: Use auto-print-make-variable

PORTNAME=`awk '$1 == "PORTNAME=" { print $2 }' Makefile`
PORTVERSION=`awk '$1 == "PORTVERSION=" { print $2 }' Makefile`
if [ 0$PORTVERSION = 0 ]; then
    PORTVERSION=`awk '$1 == "DISTVERSION=" { print $2 }' Makefile`
fi
if egrep -q '^GH_TAGNAME=' Makefile; then
    GH_TAGNAME=`awk '$1 == "GH_TAGNAME=" { print $2 }' Makefile`
fi
if egrep -q '^GH_PROJECT=' Makefile; then
    GH_PROJECT=`awk '$1 == "GH_PROJECT=" { print $2 }' Makefile`
fi
if egrep -q '^PKGNAMEPREFIX=' Makefile; then
    PKGNAMEPREFIX=`awk '$1 == "PKGNAMEPREFIX=" { print $2 }' Makefile`
    # printf "PKGNAMEPREFIX = %s\n" $PKGNAMEPREFIX
fi
DISTNAME=`awk '$1 == "DISTNAME=" { print $2 }' Makefile | \
    sed -e 's|${PKGNAMEPREFIX}|'$PKGNAMEPREFIX'|g'`

port_dir=`pwd`
# If WRKSRC is not set, assume first two components of pathname
grandparent=${port_dir%/*/*}
port=${port_dir#$grandparent/}
echo $grandparent $port
WRKSRC=`auto-print-make-variable -p $grandparent $port WRKSRC`
# Get relative path
WRKSRC=${WRKSRC#$port_dir/}

mkdir -p files

# Go to WRKSRC and generate patch file
cd $WRKSRC
file1=${filename#./$WRKSRC/}
file=${file1#$WRKSRC/}
patch_file='patch-'`echo "$file" | sed -e 's|_|__|g' | sed -e 's|/|_|g'`
printf "Writing files/$patch_file.\n"
diff -udp "$file.orig" "$file" > $port_dir/files/$patch_file || true
cd $port_dir
make makepatch
