#!/bin/sh -e

##########################################################################
#   Script description:
#       Commit a port via git
#       
#   History:
#   Date        Name        Modification
#   2021-04-12  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 category/port\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
port=$1
if ! echo $port | fgrep -q /; then
    usage
fi
category=$(echo $port | cut -d / -f 1)
makefile=$category/Makefile
echo $makefile

: ${PORTSDIR:=/usr/ports}
cd $PORTSDIR
if grep -w wip $port/Makefile | grep -v '^CATEGORIES'; then
    printf "$port contains references to wip.  Please fix and try again.\n"
    exit 1
fi
read -p "Run port-check? [y]/n " check
if [ 0$check != 0n ]; then
    cd $port
    port-check
    cd ../..
fi

git status
pause
git diff $port $makefile
pause

read -p 'Proceed with commit? y/[n] ' proceed
if [ 0$proceed = 0y ]; then
    printf "Ensuring we're on the main branch...\n"
    git checkout main
    
    cat << EOM
    
If this is a new port, copy the text below for the commmit message:

EOM
    printf "${port}: "
    grep '^COMMENT' $port/Makefile | cut -f 2-
    printf "\n"
    cat $port/pkg-descr
    pause

    git commit $port $makefile

    git status
    read -p 'Push commits? y/[n] ' push
    
    if [ 0$push = 0y ]; then
	port-push-commits
    fi
fi
