#!/bin/sh -e

if [ $# -gt 1 ]; then
    printf "Usage: $0 [dir]\n"
    exit 1
fi

if [ $# = 1 ]; then
    cd /usr/wip/$1
fi

printf "Remove distfile? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    make distclean
else
    make clean
fi
# Rebuild before deinstall to minimize uninstalled time
make
make deinstall
make install

