#!/bin/sh -e

##########################################################################
#   Synopsis:
#       port-reinstall [category/port]
#       
#   Description:
#       .B port-reinstall
#       cleans, removes, and reinstalls the port in the current working
#       directory, or the one named by category/port under $PORTSDIR,
#       which defaults to /usr/ports.
#       
#   Arguments:
#       category/port   Alternative to the CWD
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   Examples:
#       cd /usr/ports/biology/biolibc && port-reinstall
#       port-reinstall biology/biolibc
#
#   See also:
#       port-check(1), port-create(1), port-diff(1), port-mkpatch(1),
#       port-patch-edit(1), port-remake(1), port-restage(1)
##########################################################################

usage()
{
    printf "Usage: $0 [category/port]\n"
    exit 64     # sysexits(3) EX_USAGE
}


##########################################################################
#   Main
##########################################################################

if [ $# -gt 1 ]; then
    usage
fi

if [ $# = 1 ]; then
    if [ -z $PORTSDIR ]; then
	PORTSDIR=/usr/ports
    fi
    cd $PORTSDIR/$1
fi

printf "Remove distfile? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    make distclean
else
    make clean
fi
# Rebuild before deinstall to minimize uninstalled time
make
make deinstall
make install
make distclean
