#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-11-10  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 filename\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

filename="$1"
if [ ! -e pkg-descr ]; then
    printf "$0 must be run from the port directory.\n"
    exit 1
fi

if [ ! -e "$filename.orig" ]; then
    printf "Error: No $filename.orig present.\n"
    exit 1
fi

# Determine WRKSRC
PORTNAME=`awk '$1 == "PORTNAME=" { print $2 }' Makefile`
PORTVERSION=`awk '$1 == "PORTVERSION=" { print $2 }' Makefile`
if egrep -q '^PKGNAMEPREFIX=' Makefile; then
    PKGNAMEPREFIX=`awk '$1 == "PKGNAMEPREFIX=" { print $2 }' Makefile`
    # printf "PKGNAMEPREFIX = %s\n" $PKGNAMEPREFIX
fi
DISTNAME=`awk '$1 == "DISTNAME=" { print $2 }' Makefile | \
    sed -e 's|${PKGNAMEPREFIX}|'$PKGNAMEPREFIX'|g'`

if egrep -q '^WRKSRC=' Makefile; then
    WRKSRC=`awk '$1 == "WRKSRC=" { print $2 }' Makefile`
    # printf "Raw WRKSRC = %s\n" $WRKSRC
elif egrep -q '^DISTNAME=' Makefile; then
    WRKSRC=work/`awk '$1 == "DISTNAME=" { print $2 }' Makefile`
else
    WRKSRC=work/${PORTNAME}-${PORTVERSION}
fi
# Do DISTNAME before PORTNAME and PORTVERSION in case it references them.
WRKSRC=`echo $WRKSRC | sed -e 's|${WRKDIR}|work|g' \
    -e 's|${DISTNAME}|'$DISTNAME'|g' \
    -e 's|${PORTNAME}|'$PORTNAME'|g' \
    -e 's|${PORTVERSION}|'$PORTVERSION'|g'`

# printf "WRKSRC = %s\n" $WRKSRC

mkdir -p files
port_dir=`pwd`

# Go to WRKSRC and generate patch file
echo $WRKSRC
cd $WRKSRC
file=${filename#$WRKSRC/}
patch_file='patch-'`echo "$file" | sed -e 's|_|__|g' | sed -e 's|/|_|g'`
diff -uE "$file.orig" "$file" > $port_dir/files/$patch_file

